### ISSUE TITLE
JS File Request optional

### ISSUE THREAD

**Issue by sebastian-marinescu** [Jako/emo#1]
Hi @Jako, first of all nice work!

While trying this Extra I noticed: 
- I could not disable the JS script file (in case I would like to integrate the JS into a another workflow and ship it in my own assets)
- The JS file is still loaded even if no email-address is present on the page

I think one this options should be possible, what do you think?

**Comment by Jako** [comment]
The first option should be made available, the second seems to be a bit overkill.

**Comment by sebastian-marinescu** [comment]
It's also the option I'm tending to :+1:

**Comment by Jako** [comment]
Fixed with 081a8eb
