### ISSUE TITLE
Double Icons

### ISSUE THREAD

**Issue by Netzfeld** [Jako/emo#15]
With the latest version this one:
&lt;p&gt;&lt;a href=&quot;mailto:kontakt@dominname.de&quot;&gt;&lt;span class=&quot;mSpace top2 fs20 icon-envelope white&quot;&gt;&lt;/span&gt;kontakt@dominname.de&lt;/a&gt;&lt;/p&gt;

Gets this one:
&lt;p&gt;&lt;span id=&quot;_emoaddrId1&quot;&gt;&lt;a class=&quot;emo_address mSpace top2 fs20 icon-envelope white&quot; href=&quot;mailto:kontakt@dominname.de&quot;&gt;&lt;span class=&quot;mSpace top2 fs20 icon-envelope white&quot;&gt;&lt;/span&gt;kontakt@dominname.de&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;

The classes are doubled in the <a class and the Icon gets doubled
Example at https://frauenhaus-hildesheim.de/
At the top-right corner

**Comment by Jako** [comment]
The issue occurred only when the link tag itself did not contain a class attribute.

Fixed with 1.8.4. Thanks for your report!
