### ISSUE TITLE
Usage with strict content security policy

### ISSUE THREAD

**Issue by Camo30** [Jako/emo#21]
Hello @Jako,

Since a few days my website uses a very strict content security policy ([CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)) which blocks any forbidden requests. Since then I'm getting this message in the browser console because of emo: 

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-bfdm9szMledcxSa3OUnhUfxoYiiR40idmWE4sHvBcsI='), or a nonce ('nonce-...') is required to enable inline execution.

The first option with "unsafe-inline" is the baddest one in terms of security as it allows all inline scripts (as without CSP). The second one with the hash does not work here because the inline javascript code changes on every request so the hash is not stable. The third one should be the way to go as it would only be necessary to mark the inline script with a random string (maybe dynamically as a system setting) like that:

`<script nonce="rAnd0m">
	doWhatever();
</script>`

This way inline code could be enabled securely within the CSP. It should be placed here:

`<script src="assets/components/emo/js/emo.min.js?v=1.8.8"></script> <!-- This script block stores the encrypted --> <!-- email address(es) in an addresses array. --> <script type="text/javascript" nonce="rAnd0m">....</script>`

Do you think that would be feasible?

**Comment by Jako** [comment]
emo 2.8.9 is there. You can reference your own template chunk for the addresses in the emo.adresses_tpl system setting.

**Comment by Camo30** [comment]
Awesome! Works like a charm, thank you.
