### ISSUE TITLE
Issue with UTF-8 characters.

### ISSUE THREAD

**Issue by studionik73** [Jako/emo#22]
There are issues with UTF-8 characters in the obfuscation SPAN tag, like the attached image.

![Immagine 2022-06-24 130823](https://user-images.githubusercontent.com/108129029/175523040-6b7219da-0c66-4c94-94d5-e19618d93c60.png)

Thank you for your help.

**Comment by Jako** [comment]
The `ü` can be saved in the content field using different types of Unicode entities: https://en.wikipedia.org/wiki/Precomposed_character.

emo seems to have issues with decomposed characters. A precomposed `Åström` is working but a decomposed `Åström` not. Both look the same in the content field with and without an RTE.

I close this as `wontfix`.
