### ISSUE TITLE
Passing null deprecated (PHP 8.1)

### ISSUE THREAD

**Issue by marcbyte64** [Jako/emo#25]
Just a heads up that the following are deprecated in PHP 8.x:

/core/components/emo/src/Emo.php : 259) PHP deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
/core/components/emo/src/Emo.php : 151) PHP deprecated: is_nan(): Passing null to parameter #1 ($num) of type float is deprecated
/core/components/emo/src/Emo.php : 154) PHP deprecated: is_nan(): Passing null to parameter #1 ($num) of type float is deprecated

**Comment by Jako** [comment]
Fixed in 1.8.10
