### ISSUE TITLE
emo detecting image with @ in name as email

### ISSUE THREAD

**Issue by VibeDesign** [Jako/emo#27]
I just encountered a (probably) rare case of emo, catching something else than an email. The issue occurs when `@` is used in a file name:

```html
<!-- code -->
<img src="assets/img/logo-white.png" data-at2x="assets/img/logo-white@2x.png" alt="" class="logo">

<!-- output -->
<img src="assets/img/logo-white.png" data-at2x="assets/img/<span id=" _emoaddrid4"=""><span class="emo_address">Bitte Javascript aktivieren!</span>" alt="" class="logo">
```

I know, I can exclude those parts manually, just thought maybe there's a way to exclude typical file types or restrict emo to valid TLDs in a future update.

**Comment by Jako** [comment]
Fixed with [1.9.0](https://github.com/Jako/emo/commit/1a2c50b433a07bf75b3abc11fcb8eab076c44ec3)
