### ISSUE TITLE
Error: Uninitialized string offset 64

### ISSUE THREAD

**Issue by lapp** [Jako/emo#28]
Hi Jako,

just updated to version 1.9.0 on MODx 2.8.7 and PHP 8.2 and got this error in MODx error log:

`29.10.2024 | 12:50:45 | ERROR | /home/www/../core/components/emo/src/Emo.php | 159
PHP warning: Uninitialized string offset 64
`

Could you please check it?
Many thanks, Michal

**Comment by Jako** [comment]
Can you try that change please?

**Comment by lapp** [comment]
Thanks, there are no more errors, M.

**Comment by Jako** [comment]
Fixed with 1.9.1
