### ISSUE TITLE
Obfuscated plain-text-mail-addresses

### ISSUE THREAD

**Issue by sebastian-marinescu** [Jako/emo#3]
Hi Jako, 
after testing your plugin I noticed that obfuscated plain-text-mail-addresses are converted to a mailto-link at insertion. I think it should either be an option to generated links out of emails, or better yet the plain-text-mails remain plain-text. What do you think?

**Comment by Jako** [comment]
You could exclude sections between '' and '' from replacement since version 1.8.0. I hope this is more suitable than disabling this globally.
