### ISSUE TITLE
Google map links

### ISSUE THREAD

**Issue by davidpede** [Jako/emo#4]
Great plugin!

Having a problem with Google map links though. I think emo is reading the @ symbol in the link.

Map link:
`https://www.google.co.uk/maps/place/PRP+Architects/@53.479186,-2.247409,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0xddef64035c715304?hl=en`

Result:
`<p><a _emoaddrid9"="" href="https:&lt;span id="><span class="emo_address">Turn on Javascript!</span>,-2.247409,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0xddef64035c715304?hl=en" title="View Map" target="_blank"&gt;View map »</a></p>`

Thanks

**Comment by Jako** [comment]
Yes, the email regex is too simple to ignore those links.

**Comment by davidpede** [comment]
I've submitted a PR to address this issue: #6

**Comment by Jako** [comment]
Merged, thanks!
