### ISSUE TITLE
Missing files in installation via MODX Package Management

### ISSUE THREAD

**Issue by achterbahn** [Jako/emo#7]
Installation via MODX Package Management does not create the assets/components/emo/ folder and does not copy the folders/files.

**Comment by Jako** [comment]
Is the folder `assets/components` writable for PHP?

**Comment by achterbahn** [comment]
assets(775)/components(755)

**Comment by Jako** [comment]
775 or 755 means not, that PHP could write into a folder. 777 would allow every user/application to write into a folder.

But it seams that the latest package does not install the files into the assets folder for whatever reason on a local installation. I have built a new one. Could you check the 1.8.1 in https://github.com/Jako/emo-revo/tree/master/_packages

**Comment by Jako** [comment]
Fixed with 1.8.1. Thank you for reporting this.
